# Generated by Django 2.2.4 on 2019-08-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0002_auto_20190807_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover1',
            field=models.ImageField(default='DEFAULT VALUE', upload_to='images1/'),
        ),
    ]
