# Generated by Django 2.1 on 2019-08-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitation', '0004_auto_20190809_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='queen',
            field=models.CharField(default='Queen', max_length=50),
        ),
    ]
